// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "RETO RIMAC",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "api",
        "description": "",
        "operationId": "api.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/films/swapi/{id}": {
      "get": {
        "summary": "getFilmSwapi",
        "description": "",
        "operationId": "getFilmSwapi.get./films/swapi/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/films/swapi": {
      "get": {
        "summary": "getFilmsSwapi",
        "description": "",
        "operationId": "getFilmsSwapi.get./films/swapi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planets": {
      "post": {
        "summary": "addPlanet",
        "description": "",
        "operationId": "addPlanet.post./planets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/APPLICATION_JSON"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "getPlanets",
        "description": "",
        "operationId": "getPlanets.get./planets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planets/{id}": {
      "get": {
        "summary": "getPlanet",
        "description": "",
        "operationId": "getPlanet.get./planets/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};